name: Tests

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - name: 'Run tests'
        run: yarn test
      - name: 'Run linter'
        run: yarn lint
